block:
    - name: copy elasticsearch rpm
      copy:
        src: "../files/{{ el_user }}-{{ el_version }}.rpm"
        dest: "/tmp/{{ el_user }}-{{ el_version }}.rpm"
    - name: install elasticsearch
      yum:
        name: "/tmp/{{ el_user }}-{{ el_version }}.rpm"
        state: installed
    become: yes

  - name: Delete {{ el_user }} rpm package
    file:
      path: "/tmp/{{ el_user }}-{{ el_version }}.rpm"
      state: absent
    become: yes