---
#this playbook is all the whole elasticsearch
- hosts: "{{ project_name }}"
  user: otoman
  vars_files:
    - ./inventories/{{ env }}/group_vars/global.yml
    - ./inventories/{{ env }}/group_vars/{{ project_name }}.yml
  roles:
    - jar11
    - elasticsearch