---
  - name: Add aliyun yum repo
    template: src=kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo
    become: yes

  - name: Add docker yum repo
    yum_repository: name=epel description=EPEL YUM repo baseurl=https://download.docker.com/linux/centos/docker-ce.repo enabled=yes
    become: yes

  - name: repo clean
    command: yum clean all warn=False
    become: yes
  - name: repo makecache
    command: yum makecache warn=False
    become: yes

  - name: Close swap
    command: swapoff -a
    become: yes

  - name: Configure forwarding requests
    template: src={{ item }} dest="/etc/sysctl.d/"
    with_item:
      - "k8s.conf"
      - "k8s.sh"
    become: yes

  - name: Execution forwarding takes effect
    command: sysctl --system
    become: yes

  - name: Install docker
    yum: name=docker state=present
    become: yes

  - name: Start docker service
    service: name=docker state=started enabled=yes
    become: yes

  - name: Install the k8s plugin
    yum:
      name:
        - kubelet
        - kubeadm
        - kubectl
        - kubernetes-cni
      state: present
    become: yes

  - name: Start kubelet service
    service: name=kubelet state=started enabled=yes
    become: yes

  - name: Pull k8s related image
    command: sudo sh /etc/sysctl.d/k8s.sh
    become: yes

  - name: Initialize the relevant image
    command: kubeadm init --kubernetes-version=v1.11.0 --pod-network-cidr=10.244.0.0/16
    when: ansible_default_ipv4.address == "172.21.17.4"
    register: info
    become: yes

  - name: Print kubeadm info
    debug: var=result verbosity=2
    when: ansible_default_ipv4.address == "172.21.17.4"
    become: yes

  - name: Configure kubectl authentication information
    command: export KUBECONFIG=/etc/kubernetes/admin.conf
    when: ansible_default_ipv4.address == "172.21.17.4"
    become: yes

  - name: Configuration is permanently valid
    command: echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> /etc/profile
    when: ansible_default_ipv4.address == "172.21.17.4"
    become: yes

  - name: Install the flannel network
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - /etc/cni/net.d/
      - /usr/share/oci-umount/oci-umount.d
      - /run/flannel/
      - /opt/kubernetes
    when: ansible_default_ipv4.address == "172.21.17.4"
    become: yes

  - name: Copy filannel config
    copy:
      src: "{{ item.file }}"
      dest: "{{ item.dir }}/{{ item.file }}"
    with_items:
      - { file: '10-flannel.conf', dir: '/etc/cni/net.d/' }
      - { file: 'subnet.env', dir: '/run/flannel/' }
      - { file: 'flannel.yml', dir: '/opt/kubernetes' }
    when: ansible_default_ipv4.address == "172.21.17.4"
    become: yes

  - name: Create a flannel network
    command: kubectl create -f /opt/k8s/flannel.yml
    when: ansible_default_ipv4.address == "172.21.17.4"
    become: yes

  - name: Node joins k8s
    command: "{{ info.stdout_lines }}"
    when: ansible_default_ipv4.address != "172.21.17.4"
    become: yes

  - name: K8s Dashboard configuration
    git:
      repo: https://github.com/xxlaila/k8s.git
      dest: /opt/
      clone: yes
    become: yes

  - name: Create kube-system
    command: kubectl -n kube-system create -f /opt/k8s/kubernetes-dashboard/{{ item }}
    with_items:
      - heapster-rbac.yaml
      - heapster.yaml
      - kubernetes-dashboard.yaml
      - kubernetes-dashboard-admin.rbac.yaml
    when: ansible_default_ipv4.address == "172.21.17.4"
    become: yes

  - name: Start container
    command: kubectl -f /opt/k8s/kubernetes-dashboard/dashboard-admin.yaml create
    when: ansible_default_ipv4.address == "172.21.17.4"
    become: yes