---

  - name: Create {{ el_user }} data directory
    file:
      path: "{{ item.value }}/es"
      state: directory
      owner: "{{ el_user }}"
      group: "{{ el_user }}"
      mode: 0755
    with_dict: "{{ disks }}"
    become: yes

  - name: Umount datanode disks
    mount:
      path: "{{ item.value }}"
      state: absent
    with_dict: "{{ disks }}"
    become: yes

  - name: Format datanode disks
    filesystem:
      fstype: xfs
      dev: "{{ item.key }}"
      force: yes
    with_dict: "{{ disks }}"
    become: yes

  - name: Mount datanode disks
    mount:
      path: "{{ item.value }}"
      src: "{{ item.key }}"
      fstype: xfs
      opts: "defaults,noatime,nobarrier"
      state: mounted
    with_dict: "{{ disks }}"
    become: yes