---

  - name: install elasticsearch
    block:
    - name: copy elasticsearch rpm
      copy:
        src: "../files/{{ el_user }}-{{ el_version }}.rpm"
        dest: "/tmp/{{ el_user }}-{{ el_version }}.rpm"
    - name: install elasticsearch
      yum:
        name: "/tmp/elasticsearch-7.4.1-x86_64.rpm"
        state: installed
    become: yes

  - name: Delete {{ el_user }} rpm package
    file:
      path: "/tmp/{{ el_user }}-{{ el_version }}.rpm"
      state: absent
    become: yes

#  - name: Create {{ el_user }} data and logs
#      file:
#        name: "{{ item }}"
#        state: directory
#        owner: "{{ el_user }}"
#        group: "{{ el_user }}"
#        mode: 0755
#      with_items:
#        - "{{ path.logs }}"
#        - "{{ path.data }}"
#      become: yes

#  - name: copy config elasticsearch.yml
#    template:
#      src: "elasticsearch.yml.j2"
#      dest: "/etc/elasticsearch/elasticsearch.yml"
#      backup: yes
#    become: yes

