---
  - name: Create group name
    shell: grep root:x /etc/passwd
    register: grep
    failed_when: false
    changed_when: false
  - name: Create  users name
    group: name={{ user_name }} state=present
  - name: Create {{ user_name }} user add
    user: name={{ user_name }} shell=/bin/bash group={{ user_name }} password={{ user_password }}
  - name: Add {{ user_name }} goto /etc/sudoers
    lineinfile: dest=/etc/sudoers state=present regexp="^{{ user_name }}\s" line="{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
