---
  - name: View the current system kernel version
    command: uname -a
    register: mymotd
    tags: kernel
    become: yes

  - name: print system kernel version
    debug:
      var: mymotd.stdout
      verbosity: 0
    tags: kernel
    become: yes

  - name: Yum update
    yum:
      name: "*"
      state: latest
    tags: kernel
    become: yes

  - name: Import the public key of the ELRepo repository
    rpm_key:
      state: present
      key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    tags: kernel
    become: yes

  - name: Install the yum source of the ELRepo repository
    yum:
       name: http://www.elrepo.org/elrepo-release-7.0-4.el7.elrepo.noarch.rpm
       state: present
    tags: kernel
    become: yes

  - name: Install long-term support version kernel-lt.x86_64
    yum:
      name:
        - kernel-lt
        - kernel-lt-devel
      state: present
      disablerepo: "*"
      enablerepo: "elrepo-kernel"
    tags: kernel
    become: yes

  - name: Uninstall the old kernel toolkit
    yum:
      name:
        - kernel-tools-libs
        - kernel-tools
      state: absent
    tags: kernel
    become: yes

  - name: Install a new version of the toolkit
    yum:
      name: kernel-lt-tools
      state: present
      disablerepo: "*"
      enablerepo: "elrepo-kernel"
    tags: kernel
    become: yes

  - name: View the current actual boot kernel version
    command: grub2-editenv list
    register: actual
    tags: kernel
    become: yes

  - name: print actual boot kernel version
    debug:
      var: actual.stdout
      verbosity: 0
    tags: kernel
    become: yes

  - name: View all available kernels on the system
    shell: grub2-set-default  0 && grub2-mkconfig -o /etc/grub2.cfg
    register: available
    tags: kernel
    become: yes

  - debug: Print all available kernels on the system
    debug:
      var: available.stdout
      verbosity: 0
    tags: kernel
    become: yes

  - name: Set the new kernel as the default version of grub2
    command: grub2-set-default 0
    become: yes

  - name: Generate grub configuration file
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    register: grub2
    tags: kernel
    become: yes

  - name: Print the grub configuration file
    debug:
      var: grub2.stdout
      verbosity: 0
    tags: kernel
    become: yes

  - name: Restart server
    shell: sleep 2 && shutdown -r now "reboot"
    async: 1
    poll: 0
    ignore_errors: yes
    tags: kernel
    become: yes

  - include_tasks: uninstall.yml
    tags: uninstall
