- type: log
  paths:
    - {{ pro_dir }}/logs/*/*.logstash_json
  fields:
    type: access
  fields_under_root: true
  ignore_older: 5m
  tail_files: false
  max_bytes: 1024000
  close_older: 30m
  force_close_files: true
  processors:
    - drop_fields:
        fields: ['input','offset','prospector']
