---
  - name: Create {{ name }} data directory
    file:
      path: "{{ item.value }}"
      state: directory
      owner: "{{ webuser }}"
      group: "{{ webuser }}"
      mode: 0755
    with_dict: "{{ disks_data }}"
    become: yes

  - name: Umount datanode disks
    mount:
      path: "{{ item.value }}"
      state: absent
    with_dict: "{{ disks_data }}"
    become: yes

  - name: Format datanode disks
    parted:
      device: "{{ item.key }}"
      number: 1
      state: present
      label: gpt
    register: status
    with_dict: "{{ disks_data }}"
    become: yes

  - name: Format the disk as xfs
    filesystem:
      fstype: xfs
      dev: "{{ item.item.key }}1"
      force: yes
    with_items: "{{ status.results }}"
    ignore_errors: yes
    become: yes

  - name: disk uuid
    command: /usr/sbin/blkid "{{ item.key }}1"
    with_dict: "{{ disks_data }}"
    register: result
    become: yes

  - name: print disk uuid or disk path
    debug:
      msg: "{% for i in result.results %} {{ i.stdout.split(' ')[1] }} {{ i.item.value }} {% endfor%}"
    become: yes

  - name: Write to fstab
    lineinfile:
      dest: '/etc/fstab'
      line: "{{ item }}"
    with_items:
      - "{% for i in result.results %} {{ i.stdout.strip().split(' ')[1] }} {{ i.item.value }}\txfs\tdefaults,noatime,nofail\t0 0\n {% endfor %}"
    become: yes

  - name: Modify fstab parameters
    replace:
      path: '/etc/fstab'
      regexp: "{{ item }}"
      replace: ''
    with_items:
      - '"'
      - '^\s+'
    become: yes

  - name: mount disk
    command: mount -a
    become: yes

  - name: Give {{ name }} permission
    shell: "sudo chown -R {{ webuser }}:{{ webuser }} /data*"
    when: inventory_hostname in groups['cold-data'] or inventory_hostname in groups['hot-data']
    become: yes